services:

  # Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - ./portainer/data:/portainer_data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always