services:
  web:
    image: itzg/rcon
    container_name: mc-rcon
    restart: unless-stopped
    environment:
      RWA_USERNAME: ${RWA_USERNAME}
      RWA_PASSWORD: ${RWA_PASSWORD}
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: mc
      RWA_RCON_PASSWORD: ${RCON_PASSWORD}
    ports:
      - "4326:4326"
      - "4327:4327"
  mc:
    image: itzg/minecraft-server
    container_name: mc-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TZ: "Europe/Paris"
      TYPE: "PURPUR"
      VERSION: "1.21"
      SEED: 2374522903531219544
      SERVER_NAME: "Gr00v3Craft"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "6G"
      VIEW_DISTANCE: 15
      ENABLE_QUERY: "true"
      QUERY_PORT: 25565
      ENABLE_RCON: "true"
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD}
      DIFFICULTY: "hard"
      MODE: "survival"
      LEVEL_TYPE: "default"
      ONLINE_MODE: "true"
      PVP: "false"
      MAX_PLAYERS: 10
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "false"
      WHITELIST: ${WHITELIST}
      ENFORCE_WHITELIST: "true"
      OPS: ${OPS}
      USE_AIKAR_FLAGS: "true"
    volumes:
      - ./data:/data
      - ./plugins:/data/plugins