# GITHUB
alias g="git"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gl="git log"
alias gd="git diff"
alias gb="git branch"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gm="git merge"
alias gr="git rebase"
alias gcl="git clone"
alias gpo="git push origin"
alias gpl="git pull"
alias gpf="git push --force"
alias gpfu="git push --force-with-lease"